import pathlib,json,statistics,hashlib,datetime
BASE=pathlib.Path(__file__).resolve().parent;ROOT=BASE.parents[3]
raw=BASE/'round102-sustained.jsonl';runs=[json.loads(s) for s in raw.read_text().splitlines()];assert len(runs)==12
meta=json.loads((BASE/'round102-provenance.json').read_text());summary=[];experiments=[]
for store in ['memory','sqlite']:
 for variant in ['control','bounded']:
  group=[(i+1,{x['kind']:x for x in map(json.loads,r['stdout'].splitlines())}) for i,r in enumerate(runs) if r['store']==store and r['variant']==variant];assert len(group)==3
  samples=[d['sample'] for _,d in group];median=lambda key:int(statistics.median(s[key] for s in samples))
  config=dict(runtime=group[0][1]['config'],generator=variant,profile=meta['profile'],host=meta['host'],features=meta['features'])
  fingerprint=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
  metrics=dict(runtime_ns_median=median('elapsed_ns'),cpu_us_median=int(statistics.median(s['cpu_user_us']+s['cpu_system_us'] for s in samples)),memory_bytes_median=median('max_rss_bytes'),rust_live_bytes_median=None,rust_allocated_bytes_median=median('rust_allocated_bytes'),agents=4,accepted=median('successful_receipts'),rejected=int(statistics.median(s['caller_rejected']+s.get('generator_rejected',0) for s in samples)),failed=0,delivered=None)
  item=dict(store=store,variant=variant,metrics=metrics,receipt_p99_ns_median=median('successful_receipt_p99_ns'),schedule_lateness_p99_ns_median=median('schedule_lateness_p99_ns'),generator_rejected=[s.get('generator_rejected',0) for s in samples],peak_generator_tasks=[s.get('peak_generator_tasks') for s in samples]);summary.append(item)
  experiments.append(dict(id=f'round102-{store}-{variant}',label=f'{store} sustained / {variant} generator',status='measured',comparison_key=dict(workload='sustained-generator-diagnostic',store=store,durability='memory' if store=='memory' else 'DELETE/FULL/ProcessRestart',payload_bytes=128,population=4,producers=4,streams=4,subscribers=0,concurrency=256 if variant=='bounded' else 4000,page_records=1024,page_bytes=2097152,measurement_phase='existing_performance_baseline_timed_iteration',instrumentation='existing_System_GlobalAlloc_and_stage_probe',config_fingerprint=fingerprint,memory_scope='process_lifetime_peak_including_harness',cpu_scope='process_user_plus_system_timed_scope'),sample_count=3,metrics=metrics,provenance=dict(source_path=str(raw.relative_to(ROOT)),source_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),sample_key=json.dumps(dict(lines=[line for line,_ in group],aggregation='median_per_metric',binary_sha256=meta['binary_sha256'][variant])),source_epoch=meta['archive_sha256'][variant]),note='Harness comparison only; library source unchanged. Four active producers, not 100k active-agent qualification. Generator cap can reject before runtime; counts are retained separately in raw results. Different generator configurations are not chart-connected.'))
(BASE/'round102-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
p=ROOT/'verification/evidence/home.json';d=json.loads(p.read_text());assert d['rounds'][-1]['number']==101
d['rounds'].append(dict(number=102,status='measured',build_id=meta['binary_sha256']['bounded'],experiments=experiments,summary='Replaced sustained harness future-task allocation with a fixed 256-task generator and explicit generator rejections. Three interleaved fresh samples on each store/generator retain outcomes, scheduling delay, latency, CPU and memory. Harness change only; no library speedup or sustained large-population qualification claimed. See round102 report.'))
d['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(summary,indent=2))
