import pathlib,json,hashlib,statistics,datetime,shutil
r=pathlib.Path.cwd();ev=next((r/'docs/adr').glob('002-*'))/'evidence';p=ev/'round94-burst.jsonl';raw=p.read_bytes();runs=[json.loads(x) for x in raw.splitlines()];assert runs[-1]['kind']=='completion' and runs[-1]['runs']==18;meta=json.loads((ev/'round94-provenance.json').read_text());groups={}
for line,run in enumerate(runs[:-1],1):
 assert run['exit_code']==0
 data={x['kind']:x for x in map(json.loads,run['stdout'].splitlines())};s=data['sample'];res=data['resources'];n=run['tasks']
 assert s['offered']==n==s['append_tasks']==res['burst_ready_tasks']
 assert s['successful_receipts']+s['caller_rejected']+s['caller_failed']==n
 assert s['runtime_failed']==s['caller_failed']==0 and s['inserted']==s['successful_receipts']
 assert s['peak_queued_appends']<=1024 and s['shutdown_queued_appends']==0 and s['shutdown_admission_waiters']==0
 assert res['shutdown_closed'] and res['shutdown_unresolved']==0
 groups.setdefault((run['store'],n),[]).append((line,data))
experiments=[];summary=[]
for (store,n),pairs in sorted(groups.items()):
 samples=[d['sample'] for _,d in pairs];resources=[d['resources'] for _,d in pairs];assert len(samples)==3
 med=lambda key:int(statistics.median(s[key] for s in samples));resource_med=lambda key:int(statistics.median(s[key] for s in resources));cfg=pairs[0][1]['config'];environment=pairs[0][1]['environment'];config={'runtime':cfg,'tasks':n,'payload_bytes':128,'events_per_task':1,'barrier':'ready_then_release','harness':'large_Outcome_per_task_v1','cpu':environment['cpu'],'host':meta['host'],'power':'AC' if 'AC Power' in meta['power'] else 'battery','features':meta['features']};identity=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
 metrics={'runtime_ns_median':med('elapsed_ns'),'cpu_us_median':int(statistics.median(s['cpu_user_us']+s['cpu_system_us'] for s in samples)),'memory_bytes_median':med('max_rss_bytes'),'rust_live_bytes_median':None,'rust_allocated_bytes_median':med('rust_allocated_bytes'),'agents':n,'accepted':med('runtime_accepted'),'rejected':med('caller_rejected'),'failed':0,'delivered':None}
 record={'store':store,'tasks':n,'metrics':metrics,'accepted_range':[min(s['runtime_accepted'] for s in samples),max(s['runtime_accepted'] for s in samples)],'successful_p99_ns_median':med('successful_receipt_p99_ns'),'setup_runtime_ns_median':med('setup_elapsed_ns'),'ready_rust_delta_bytes_median':resource_med('burst_ready_rust_requested_live_delta_bytes'),'startup_rss_bytes_median':resource_med('startup_rss_bytes'),'ready_rss_bytes_median':resource_med('burst_ready_rss_bytes'),'startup_threads':[x['startup_threads'] for x in resources],'peak_queue':[s['peak_queued_appends'] for s in samples]};summary.append(record)
 experiments.append({'id':identity[:16],'label':f'{store} · simultaneous burst · {n:,} tasks','status':'measured','comparison_key':{'workload':'agent_burst_large_outcome_harness_v1','store':store,'durability':'ephemeral' if store=='memory' else 'ProcessRestart_DELETE_FULL','payload_bytes':128,'population':n,'producers':n,'streams':n,'subscribers':0,'concurrency':n,'page_records':0,'page_bytes':2097152,'measurement_phase':'burst task setup, barrier release, all request outcomes and profiler sampling; excludes stream setup and shutdown','instrumentation':'RustGlobalAlloc_atomic_counters+stage_timestamp_probe','config_fingerprint':identity,'memory_scope':'process_lifetime_peak_including_harness_and_setup','cpu_scope':'process_user_plus_system_timed_scope'},'sample_count':3,'metrics':metrics,'provenance':{'source_path':str(p.relative_to(r)),'source_sha256':hashlib.sha256(raw).hexdigest(),'sample_key':json.dumps({'lines':[i for i,_ in pairs],'aggregation':'median_per_metric','config':config},sort_keys=True),'source_epoch':meta['source_archive_sha256']},'note':'Three fresh archived-process runs. Each task issues one try_append; queue fixed1024. Most10k/100krequests reject. This is overload handling, not sustained active-agent capacity. Total process peak includes large per-task harness Outcome and Tokio allocations; ready task Rust delta about155.8MB at100k is not attributable to core alone. CPU/latency sampling includes harness. No throughput improvement inferred from rejections; no comparative library speedup claim.'})
(ev/'round94-summary.json').write_text(json.dumps(summary,indent=2)+'\n');hp=r/'verification/evidence/home.json';h=json.loads(hp.read_text());assert h['rounds'][-1]['number']==93;h['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();h['rounds'].append({'number':94,'status':'measured','build_id':meta['binary_sha256'],'experiments':experiments,'summary':'18fresh burst processes at1k/10k/100k tasks onMemory/SQLite pass outcome conservation, bounded1024queue and shutdown checks. Large bursts mostly reject rather than commit; not100k successful-producer support. Process RSS includes ~155.8MB ready-task Rust allocations from harness/Tokio at100k. Recorded6measured cells and acceptance/rejection alongside time/memory. Harness memory reduction being implemented separately; no library improvement claim.'});hp.write_text(json.dumps(h,indent=2)+'\n')
shutil.copyfile('/tmp/event-stream-round94-run.py',ev/'round94-run.py');shutil.copyfile('/tmp/event-stream-round94-export.py',ev/'round94-export.py');shutil.copyfile('/tmp/event-stream-round94-build.log',ev/'round94-build.log')
for s in summary:print(s['store'],s['tasks'],'accepted',s['accepted_range'],'runtime_ms',s['metrics']['runtime_ns_median']/1e6,'RSSMiB',s['metrics']['memory_bytes_median']/2**20,'threads',s['startup_threads'])
