import pathlib,json,statistics,hashlib,datetime,shutil
r=pathlib.Path.cwd();ev=r/'docs/adr/002-resource-budgets-and-performance-evidence/evidence';p=ev/'round95-paired.jsonl';raw=p.read_bytes();runs=[json.loads(x) for x in raw.splitlines()];assert runs[-1]['kind']=='completion' and runs[-1]['runs']==12;meta=json.loads((ev/'round95-provenance.json').read_text());groups={}
for line,run in enumerate(runs[:-1],1):
 assert run['exit_code']==0
 d={x['kind']:x for x in map(json.loads,run['stdout'].splitlines())};s=d['sample'];x=d['resources']
 assert s['offered']==s['append_tasks']==x['burst_ready_tasks']==100000
 assert s['successful_receipts']+s['caller_rejected']+s['caller_failed']==100000
 assert s['runtime_failed']==s['caller_failed']==0 and s['inserted']==s['successful_receipts']
 assert s['peak_queued_appends']<=1024 and s['shutdown_queued_appends']==s['shutdown_admission_waiters']==0
 assert x['shutdown_closed'] and x['shutdown_unresolved']==0
 assert s['all_outcome_latency_samples']==100000 and s['successful_receipt_samples']==s['successful_receipts'] and s['rejected_samples']==s['caller_rejected']
 groups.setdefault((run['store'],run['variant']),[]).append((line,d))
summary=[];exps=[]
for (store,variant),pairs in sorted(groups.items()):
 ss=[d['sample'] for _,d in pairs];rr=[d['resources'] for _,d in pairs];assert len(ss)==3
 med=lambda k:int(statistics.median(s[k] for s in ss));rm=lambda k:int(statistics.median(s[k] for s in rr));cfg={'runtime':pairs[0][1]['config'],'tasks':100000,'harness_variant':variant,'features':meta['features'],'host':meta['host'],'cpu':pairs[0][1]['environment']['cpu'],'scope':'one-shot_barrier_try_append_128bytes'};key=hashlib.sha256(json.dumps(cfg,sort_keys=True).encode()).hexdigest()
 metrics={'runtime_ns_median':med('elapsed_ns'),'cpu_us_median':int(statistics.median(s['cpu_user_us']+s['cpu_system_us'] for s in ss)),'memory_bytes_median':med('max_rss_bytes'),'rust_live_bytes_median':None,'rust_allocated_bytes_median':med('rust_allocated_bytes'),'agents':100000,'accepted':med('runtime_accepted'),'rejected':med('caller_rejected'),'failed':0,'delivered':None}
 summary.append({'store':store,'variant':variant,'metrics':metrics,'ready_task_rust_bytes':rm('burst_ready_rust_requested_live_delta_bytes'),'ready_rss_bytes':rm('burst_ready_rss_bytes'),'accepted_range':[min(s['runtime_accepted'] for s in ss),max(s['runtime_accepted'] for s in ss)],'success_p99_ns':med('successful_receipt_p99_ns')})
 exps.append({'id':key[:16],'label':f'{store} · {variant} harness · 100,000 tasks','status':'measured','comparison_key':{'workload':'paired_burst_caller_layout_'+variant,'store':store,'durability':'ephemeral' if store=='memory' else 'ProcessRestart_DELETE_FULL','payload_bytes':128,'population':100000,'producers':100000,'streams':100000,'subscribers':0,'concurrency':100000,'page_records':0,'page_bytes':2097152,'measurement_phase':'burst task setup, release, outcomes and profiling; excludes stream setup/shutdown','instrumentation':'Rust_GlobalAlloc+stage_probe;'+variant+'_task_layout','memory_scope':'process_lifetime_peak_including_harness','cpu_scope':'process_user_plus_system_timed_scope','config_fingerprint':key},'sample_count':3,'metrics':metrics,'provenance':{'source_path':str(p.relative_to(r)),'source_sha256':hashlib.sha256(raw).hexdigest(),'sample_key':json.dumps({'lines':[n for n,_ in pairs],'aggregation':'median_per_metric','binary_sha256':meta['binary_sha256'][variant],'config':cfg},sort_keys=True),'source_epoch':meta['archive_sha256'][variant]},'note':'Controlled caller/harness-only change; production library files identical. Large bursts still mostly reject at1024queue. Memory savings are not a core-library speedup. All100k latency outcomes and accepted/rejected sample counts conserved. Fresh paired runs alternate variant order. RSS includes allocator retention and profiling, not just library state.'})
(ev/'round95-summary.json').write_text(json.dumps(summary,indent=2)+'\n');hp=r/'verification/evidence/home.json';h=json.loads(hp.read_text());assert h['rounds'][-1]['number']==94;h['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();h['rounds'].append({'number':95,'status':'measured','build_id':None,'experiments':exps,'summary':'12fresh paired100k-task runs compare identical library with baseline/compact harness. Ready task Rust allocation delta falls155,839,050→40,639,050bytes:115.2MB saved. Alloutcome/latency counts, fixedqueue and shutdown checks pass. This is caller/harness memory reduction; large bursts still mostly reject, so no100ksuccessful-producer or core speedup claim. Four measured paired cells added.'});hp.write_text(json.dumps(h,indent=2)+'\n')
for n in ('run','export'):shutil.copyfile('/tmp/event-stream-round95-'+n+'.py',ev/('round95-'+n+'.py'))
shutil.copyfile('/tmp/event-stream-round95-build.log',ev/'round95-build.log')
for s in summary:print(s['store'],s['variant'],'RSSMiB',s['metrics']['memory_bytes_median']/2**20,'runtime_ms',s['metrics']['runtime_ns_median']/1e6,'accepted',s['accepted_range'],'ready',s['ready_task_rust_bytes'])
