import pathlib,json,hashlib,datetime
BASE=pathlib.Path(__file__).resolve().parent;ROOT=BASE.parents[3];raw=BASE/'round104-population.jsonl'
runs=[json.loads(line) for line in raw.read_text().splitlines()];assert len(runs)==6
meta=json.loads((BASE/'round104-provenance.json').read_text());experiments=[];summary=[]
for line,run in enumerate(runs,1):
 data={r['kind']:r for r in map(json.loads,run['stdout'].splitlines())};s=data['sample'];v=data['population_verification'];store=run['store'];n=run['population']
 config=dict(runtime=data['config'],population=data['population_config'],host=meta['host'],features='all-features',cycles=2,interval_us=5000)
 fingerprint=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
 metrics=dict(runtime_ns_median=s['elapsed_ns'],cpu_us_median=s['cpu_user_us']+s['cpu_system_us'],memory_bytes_median=s['max_rss_bytes'],rust_live_bytes_median=None,rust_allocated_bytes_median=s['rust_allocated_bytes'],agents=n,accepted=s['successful_receipts'],rejected=s['caller_rejected']+s['generator_rejected'],failed=s['caller_failed'],delivered=None)
 summary.append(dict(store=store,population=n,metrics=metrics,verification=v,setup_elapsed_ns=s['setup_elapsed_ns'],receipt_p99_ns=s['successful_receipt_p99_ns'],schedule_lateness_p99_ns=s['schedule_lateness_p99_ns'],peak_generator_tasks=s['peak_generator_tasks']))
 experiments.append(dict(id=f'round104-{store}-{n}',label=f'{store} / {n} rotating streams / two cycles',status='measured',comparison_key=dict(workload='population-sustained-two-cycle-diagnostic',store=store,durability='memory' if store=='memory' else 'DELETE/FULL/ProcessRestart',payload_bytes=128,population=n,producers=4,streams=n,subscribers=0,concurrency=256,page_records=v['page_max_records'],page_bytes=v['page_max_bytes'],measurement_phase='active_arrivals_and_commits_excludes_verification',instrumentation='System_GlobalAlloc_stage_probe_and_population_receipt_ledger',config_fingerprint=fingerprint,memory_scope='process_lifetime_peak_including_setup_harness_and_history',cpu_scope='process_user_plus_system_active_scope'),sample_count=1,metrics=metrics,provenance=dict(source_path=str(raw.relative_to(ROOT)),source_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),sample_key=json.dumps(dict(line=line,binary_sha256=meta['binary_sha256'])),source_epoch=meta['archive_sha256']),note='Single diagnostic sample, no repeated qualification. Two visits per stream at800 aggregate offers/s; not800/s per agent. Runtime receipt ledger is harness-owned. Exact per-stream replay verified separately after active timing. No subscribers or mixed recovery work.'))
(BASE/'round104-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
p=ROOT/'verification/evidence/home.json';d=json.loads(p.read_text());assert d['rounds'][-1]['number']==103
d['rounds'].append(dict(number=104,status='partial',build_id=meta['binary_sha256'],experiments=experiments,summary='Added rotating population_sustained with bounded tasks, actual receipt ledger, per-cycle outcomes and exact per-stream replay verification. First1k/10k/100k two-cycle Memory/SQLite diagnostics recorded as single samples. Sparse800/s aggregate workload; repeated population qualification, mixed-feature budgets and throughput limits remain open.'))
d['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(summary,indent=2))
