import pathlib,json,hashlib,datetime,statistics
BASE=pathlib.Path(__file__).resolve().parent;ROOT=BASE.parents[3];raw=BASE/'round106-population.jsonl'
runs=[json.loads(line) for line in raw.read_text().splitlines()];assert len(runs)==6
meta=json.loads((BASE/'round106-provenance.json').read_text());experiments=[];summary=[]
for store in ['memory','sqlite']:
 group=[(line,run) for line,run in enumerate(runs,1) if run['store']==store];assert len(group)==3
 rows=[{r['kind']:r for r in map(json.loads,run['stdout'].splitlines())} for _,run in group]
 data=rows[0];n=10000;v=data['population_verification']
 s={key:statistics.median(row['sample'][key] for row in rows) for key in ['elapsed_ns','cpu_user_us','cpu_system_us','max_rss_bytes','rust_allocated_bytes','successful_receipts','caller_rejected','generator_rejected','caller_failed','setup_elapsed_ns','successful_receipt_p99_ns','schedule_lateness_p99_ns','peak_generator_tasks']}
 config=dict(runtime=data['config'],population=data['population_config'],host=meta['host'],features='all-features',cycles=2,interval_us=1000)
 fingerprint=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
 metrics=dict(runtime_ns_median=s['elapsed_ns'],cpu_us_median=s['cpu_user_us']+s['cpu_system_us'],memory_bytes_median=s['max_rss_bytes'],rust_live_bytes_median=None,rust_allocated_bytes_median=s['rust_allocated_bytes'],agents=n,accepted=s['successful_receipts'],rejected=s['caller_rejected']+s['generator_rejected'],failed=s['caller_failed'],delivered=None)
 summary.append(dict(store=store,population=n,metrics=metrics,verification_by_run=[row["population_verification"] for row in rows],setup_elapsed_ns=s['setup_elapsed_ns'],receipt_p99_ns=s['successful_receipt_p99_ns'],schedule_lateness_p99_ns=s['schedule_lateness_p99_ns'],peak_generator_tasks=s['peak_generator_tasks']))
 experiments.append(dict(id=f'round106-{store}-{n}',label=f'{store} / {n} rotating streams / two cycles',status='measured',comparison_key=dict(workload='population-sustained-two-cycle-4000ps-diagnostic',store=store,durability='memory' if store=='memory' else 'DELETE/FULL/ProcessRestart',payload_bytes=128,population=n,producers=4,streams=n,subscribers=0,concurrency=256,page_records=v['page_max_records'],page_bytes=v['page_max_bytes'],measurement_phase='active_arrivals_and_commits_excludes_verification',instrumentation='System_GlobalAlloc_stage_probe_and_population_receipt_ledger',config_fingerprint=fingerprint,memory_scope='process_lifetime_peak_including_setup_harness_and_history',cpu_scope='process_user_plus_system_active_scope'),sample_count=3,metrics=metrics,provenance=dict(source_path=str(raw.relative_to(ROOT)),source_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),sample_key=json.dumps(dict(lines=[line for line,_ in group],aggregation='median_per_metric; counts_are_medians_not_totals',binary_sha256=meta['binary_sha256'])),source_epoch=meta['archive_sha256']),note='Three fresh diagnostic samples. Two visits per stream at4000 aggregate offers/s; not4000/s per agent. Counts are medians; see raw per-cycle outcomes and coverage. Runtime receipt ledger is harness-owned. Exact per-stream replay verified separately after active timing. No subscribers or mixed recovery work.'))
(BASE/'round106-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
p=ROOT/'verification/evidence/home.json';d=json.loads(p.read_text());assert d['rounds'][-1]['number']==105
d['rounds'].append(dict(number=106,status='partial',build_id=meta['binary_sha256'],experiments=experiments,summary='Repeated 10k-stream population at4000 aggregate offers/s on both stores, three fresh processes each. Exact accepted-history verification and bounded generator/queue checks. Full rate/population matrix, settled memory and release budgets remain open.'))
d['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(summary,indent=2))
