import pathlib,json,statistics,hashlib,datetime
BASE=pathlib.Path(__file__).resolve().parent;ROOT=BASE.parents[3]
raw=BASE/'round103-sustained.jsonl';runs=[json.loads(s) for s in raw.read_text().splitlines()];assert len(runs)==6
meta=json.loads((BASE/'round103-provenance.json').read_text());summary=[];experiments=[]
for store in ['memory','sqlite']:
 group=[(i+1,{x['kind']:x for x in map(json.loads,r['stdout'].splitlines())}) for i,r in enumerate(runs) if r['store']==store];assert len(group)==3
 samples=[d['sample'] for _,d in group];median=lambda key:int(statistics.median(s[key] for s in samples))
 config=dict(runtime=group[0][1]['config'],profile=meta['profile'],host=meta['host'],features='all-features')
 fingerprint=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
 metrics=dict(runtime_ns_median=median('elapsed_ns'),cpu_us_median=int(statistics.median(s['cpu_user_us']+s['cpu_system_us'] for s in samples)),memory_bytes_median=median('max_rss_bytes'),rust_live_bytes_median=None,rust_allocated_bytes_median=median('rust_allocated_bytes'),agents=4,accepted=median('successful_receipts'),rejected=int(statistics.median(s['caller_rejected']+s['generator_rejected'] for s in samples)),failed=0,delivered=None)
 summary.append(dict(store=store,metrics=metrics,receipt_p99_ns_median=median('successful_receipt_p99_ns'),receipt_p99_ns_range=[min(s['successful_receipt_p99_ns'] for s in samples),max(s['successful_receipt_p99_ns'] for s in samples)],schedule_lateness_p99_ns_median=median('schedule_lateness_p99_ns'),peak_generator_tasks=[s['peak_generator_tasks'] for s in samples],post_shutdown_rss_bytes=[s['post_shutdown_rss_bytes'] for s in samples]))
 experiments.append(dict(id=f'round103-{store}',label=f'{store} sustained / 60 seconds',status='measured',comparison_key=dict(workload='sustained-minute-diagnostic',store=store,durability='memory' if store=='memory' else 'DELETE/FULL/ProcessRestart',payload_bytes=128,population=4,producers=4,streams=4,subscribers=0,concurrency=256,page_records=1024,page_bytes=2097152,measurement_phase='existing_performance_baseline_timed_iteration',instrumentation='existing_System_GlobalAlloc_and_stage_probe',config_fingerprint=fingerprint,memory_scope='process_lifetime_peak_including_harness',cpu_scope='process_user_plus_system_timed_scope'),sample_count=3,metrics=metrics,provenance=dict(source_path=str(raw.relative_to(ROOT)),source_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),sample_key=json.dumps(dict(lines=[line for line,_ in group],aggregation='median_per_metric',binary_sha256=meta['binary_sha256'])),source_epoch=meta['archive_sha256']),note='One-minute four-stream diagnostic. No subscribers, cleanup or population rotation. Post-shutdown memory is immediate and includes harness state, not a settled leak test. This does not qualify 100k active agents or complete release budgets.'))
(BASE/'round103-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
p=ROOT/'verification/evidence/home.json';d=json.loads(p.read_text());assert d['rounds'][-1]['number']==102
d['rounds'].append(dict(number=103,status='measured',build_id=meta['binary_sha256'],experiments=experiments,summary='Six fresh one-minute sustained runs on four streams with bounded generator. Each offered 48000 events; raw outcome counts, task/queue bounds, shutdown, CPU, memory and latency are retained. Two measured Home cells. This exercises longer duration beyond the former16384-offer cap; rotating 1k/10k/100k population, settled memory and release budgets remain open.'))
d['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(summary,indent=2))
