import pathlib,json,hashlib,statistics,datetime
BASE=pathlib.Path(__file__).resolve().parent;ROOT=BASE.parents[3];raw=BASE/'round105-cleanup.jsonl'
rows=[json.loads(line) for line in raw.read_text().splitlines()];assert len(rows)==10
meta=json.loads((BASE/'round105-provenance.json').read_text());experiments=[];summary=[]
for variant in ['control','bounded']:
 group=[(i+1,r) for i,r in enumerate(rows) if r['variant']==variant];assert len(group)==5
 median=lambda k:int(statistics.median(r[k] for _,r in group))
 metrics=dict(runtime_ns_median=median('elapsed_ns'),cpu_us_median=median('cpu_us'),memory_bytes_median=median('process_lifetime_max_rss_bytes'),rust_live_bytes_median=None,rust_allocated_bytes_median=median('allocated_bytes'),agents=1,accepted=None,rejected=None,failed=0,delivered=None)
 summary.append(dict(variant=variant,metrics=metrics,elapsed_ns_range=[min(r['elapsed_ns'] for _,r in group),max(r['elapsed_ns'] for _,r in group)]))
 config=dict(variant=variant,records=100000,floor=256,row_limit=1,byte_limit=2097152,features='all-features',host=meta['host'])
 experiments.append(dict(id=f'round105-{variant}',label=f'Memory retention cleanup / {variant}',status='measured',comparison_key=dict(workload='retention-timestamp-suffix-cleanup',store='memory',durability='memory',payload_bytes=1,population=1,producers=1,streams=1,subscribers=0,concurrency=1,page_records=1,page_bytes=2097152,measurement_phase='256_cleanup_calls_excludes_history_setup_and_replay',instrumentation='System_GlobalAlloc_and_1ms_RSS_sampler',config_fingerprint=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest(),memory_scope='process_lifetime_peak_including_setup_and_harness',cpu_scope='process_user_plus_system_including_sampler_startup'),sample_count=5,metrics=metrics,provenance=dict(source_path=str(raw.relative_to(ROOT)),source_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),sample_key=json.dumps(dict(lines=[n for n,_ in group],aggregation='median_per_metric',binary_sha256=meta['binary_sha256'][variant])),source_epoch=meta['archive_sha256'][variant]),note='Five interleaved fresh-process samples. Measures256 one-row cleanup calls against100k records, not append throughput. Both variants verify99744 surviving records. CPU/allocation include profiler startup; wall timing excludes it. Lifetime RSS includes setup. Separate variant keys avoid two baselines at one chart round.'))
(BASE/'round105-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
p=ROOT/'verification/evidence/home.json';d=json.loads(p.read_text());assert d['rounds'][-1]['number']==104
d['rounds'].append(dict(number=105,status='measured',build_id=meta['binary_sha256']['bounded'],experiments=experiments,summary='Replaced full timestamp-index retention scans with row-budgeted ordered removal. Regression preserves timestamps for physically unreclaimed records and original suffix ages. Ten isolated before/after samples verify identical surviving history. Two measured Home cells; benchmark covers cleanup only. Broader repeated population/mixed release gates remain open.'))
d['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(summary,indent=2))
