import pathlib,json,statistics,hashlib,datetime,os,shutil
r=pathlib.Path.cwd();ev=r/'docs/adr/005-snapshots-and-consumer-recovery/evidence';p=ev/'round93-snapshot.jsonl';raw=p.read_bytes();rows=[json.loads(line) for line in raw.splitlines()];completion=rows[-1];assert completion['rows']==48 and completion['failures']==0 and completion['latency_gate_failures']==0
meta=json.loads((ev/'round93-provenance.json').read_text());harness=hashlib.sha256(pathlib.Path('/tmp/event-stream-round93-snapshot-source/examples/snapshot_resource.rs').read_bytes()).hexdigest();samples={}
for line,row in enumerate(rows,1):
 if row['kind'] not in ('snapshot_resource_sample','snapshot_foreground_sample') or not row['instrumented']:continue
 key=(row['store'],row.get('mode','full'),row['snapshot_bytes']);samples.setdefault(key,[]).append((line,row))
experiments=[];report=[]
for (store,mode,size),values in sorted(samples.items()):
 rs=[v for _,v in values];assert len(rs)==3
 scope=rs[0].get('aggregate_scope',rs[0].get('timing_scope'));cfg={'mode':mode,'snapshot_bytes':size,'chunk_bytes':65536,'store':store,'scope':scope,'features':meta['features'],'harness_sha256':harness,'cpu':meta['cpu'],'memory_bytes':meta['memory_bytes'],'host':meta['host'],'power':'AC' if 'AC Power' in meta['power'] else 'battery','instrumented':True}
 fingerprint=hashlib.sha256(json.dumps(cfg,sort_keys=True).encode()).hexdigest();med=lambda key:int(statistics.median(v[key] for v in rs))
 metrics={'runtime_ns_median':med('elapsed_ns'),'cpu_us_median':int(statistics.median(v['cpu_user_us']+v['cpu_system_us'] for v in rs)),'memory_bytes_median':med('sampled_peak_rss_bytes'),'rust_live_bytes_median':med('sampled_peak_rust_live_bytes'),'rust_allocated_bytes_median':med('allocated_bytes'),'agents':None,'accepted':256 if mode!='full' else None,'rejected':0 if mode!='full' else None,'failed':0 if mode!='full' else None,'delivered':None}
 experiments.append({'id':fingerprint[:16],'label':f'{store} · {mode} · {size//(1<<20)} MiB','status':'measured','comparison_key':{'workload':'snapshot_matrix_v2_'+mode,'store':store,'durability':'ephemeral' if store=='memory' else 'ProcessRestart_DELETE_FULL','payload_bytes':128,'population':size,'producers':0 if mode=='full' else 4,'streams':1,'subscribers':0,'concurrency':1 if mode=='full' else 4,'page_records':256,'page_bytes':2097152,'measurement_phase':scope,'instrumentation':'Rust_allocations+1ms_sampler+SQLite_VFS_sync_timeline_when_SQLite','memory_scope':'sampled_peak_process_RSS','cpu_scope':'process_user_plus_system_in_timed_scope','config_fingerprint':fingerprint},'sample_count':3,'metrics':metrics,'provenance':{'source_path':str(p.relative_to(r)),'source_sha256':hashlib.sha256(raw).hexdigest(),'sample_key':json.dumps({'lines':[n for n,_ in values],'schedule_indexes':[v['schedule_index'] for v in rs],'aggregation':'median_per_metric','config':cfg},sort_keys=True),'source_epoch':completion['source_archive_sha256']},'note':'Fresh fixed48process matrix: all correctness and12 unchanged foreground gates pass. Historical failed run retained; no causal speedup claim. Population is snapshot bytes, not agents. Four closed-loop producers in foreground mode. RSS is sampled process peak; Rust allocations exclude SQLite C heap. Per-metric medians are not one run. New harness fingerprint separates older incompatible instrumentation; this is not full product resource qualification.'})
 report.append({'store':store,'mode':mode,'snapshot_bytes':size,'metrics':metrics,'p99_ms':[v['append_p99_ns']/1e6 for v in rs] if mode!='full' else None})
(ev/'round93-summary.json').write_text(json.dumps({'completion':completion,'cells':report},indent=2)+'\n')
hp=r/'verification/evidence/home.json';home=json.loads(hp.read_text());assert home['rounds'][-1]['number']==92;home['generated_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();home['rounds'].append({'number':93,'status':'measured','build_id':completion['binary_sha256_after'],'experiments':experiments,'summary':'Archived release snapshot matrix completed48/48correctness and12/12unchanged latency/overlap gates. SQLite verify p99 3.12–3.22ms. 64MiB snapshot sampled RSS medians:SQLite10.92MiB,Memory84.38MiB. Added14fresh measured cells; no reuse of older samples. Historical round25 failure retained, no causalfix claim. Fullmixed/100kactive/resource budgets remain open.'});hp.write_text(json.dumps(home,indent=2)+'\n')
for name in ('build','run'):shutil.copyfile('/tmp/event-stream-round93-'+name+'.log',ev/('round93-'+name+'.log'))
shutil.copyfile('/tmp/event-stream-round93-export.py',ev/'round93-export.py')
print('Added',len(experiments),'cells; Home experiments',sum(len(x['experiments']) for x in home['rounds']))
